name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get current version
        id: version
        run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - run: echo ${{steps.version.outputs.prop}}
      - name: Get lunatic-model version
        id: lunatic
        run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Install lunatic-model
        run: mvn install:install-file -Dfile=lib/lunatic-model-${{steps.lunatic.outputs.prop}}.jar -DgroupId=fr.insee.lunatic -DartifactId=lunatic-model -Dversion=${{steps.lunatic.outputs.prop}} -Dpackaging=jar
      - name: Build with Maven
        run: mvn install --file pom.xml
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar